#!/usr/bin/env bash

if [[ -z ${1} || -z ${2} ]]; then
	echo "usage: $0 str1 str2"
	exit 1
fi

. /usr/share/kdel10n-scripts/common.sh

pushd "${KDEREPO_PATH}/trunk" > /dev/null || exit 1

echo "Updating repositories at \"${KDEREPO_PATH}/trunk\""
svn up || exit 1

popd > /dev/null

pushd "${KDEREPO_PATH}/trunk/l10n-support/cs/summit" > /dev/null || exit 1

echo "Seaching for string \"msgid:${1}\" with \"msgstr:${2}\""
${POSIEVE} find-messages -s "msgid:${1}" -s "msgstr:${2}" -s lokalize messages > /dev/null

popd > /dev/null
