#!/usr/bin/env bash

if [[ -z ${1} ]]; then
	echo "usage: $0 str"
	exit 1
fi

. _PREFIX_/share/kdel10n-scripts/common.sh

pushd "${KDEREPO_PATH}/trunk" > /dev/null || exit 1

echo "Updating repositories at \"${KDEREPO_PATH}/trunk\""
svn up || exit 1

popd > /dev/null

pushd "${KDEREPO_PATH}/trunk/l10n-support/cs/summit" > /dev/null || exit 1

echo "Seaching for string \"${1}\""
${POSIEVE} find-messages -s "msgstr:${1}" -s lokalize messages > /dev/null

popd > /dev/null
